# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator.serviceAccountName" . }}
  namespace: {{ include "operator.namespace" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
{{- with .Values.image.pullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
