//go:build !ignore_autogenerated

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 tjorri

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContributingPeer) DeepCopyInto(out *ContributingPeer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContributingPeer.
func (in *ContributingPeer) DeepCopy() *ContributingPeer {
	if in == nil {
		return nil
	}
	out := new(ContributingPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LokiTenantOverride) DeepCopyInto(out *LokiTenantOverride) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LokiTenantOverride.
func (in *LokiTenantOverride) DeepCopy() *LokiTenantOverride {
	if in == nil {
		return nil
	}
	out := new(LokiTenantOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LokiTenantOverride) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LokiTenantOverrideList) DeepCopyInto(out *LokiTenantOverrideList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LokiTenantOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LokiTenantOverrideList.
func (in *LokiTenantOverrideList) DeepCopy() *LokiTenantOverrideList {
	if in == nil {
		return nil
	}
	out := new(LokiTenantOverrideList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LokiTenantOverrideList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LokiTenantOverrideSpec) DeepCopyInto(out *LokiTenantOverrideSpec) {
	*out = *in
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LokiTenantOverrideSpec.
func (in *LokiTenantOverrideSpec) DeepCopy() *LokiTenantOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(LokiTenantOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LokiTenantOverrideStatus) DeepCopyInto(out *LokiTenantOverrideStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContributingPeers != nil {
		in, out := &in.ContributingPeers, &out.ContributingPeers
		*out = make([]ContributingPeer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LokiTenantOverrideStatus.
func (in *LokiTenantOverrideStatus) DeepCopy() *LokiTenantOverrideStatus {
	if in == nil {
		return nil
	}
	out := new(LokiTenantOverrideStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MimirTenantOverride) DeepCopyInto(out *MimirTenantOverride) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MimirTenantOverride.
func (in *MimirTenantOverride) DeepCopy() *MimirTenantOverride {
	if in == nil {
		return nil
	}
	out := new(MimirTenantOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MimirTenantOverride) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MimirTenantOverrideList) DeepCopyInto(out *MimirTenantOverrideList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MimirTenantOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MimirTenantOverrideList.
func (in *MimirTenantOverrideList) DeepCopy() *MimirTenantOverrideList {
	if in == nil {
		return nil
	}
	out := new(MimirTenantOverrideList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MimirTenantOverrideList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MimirTenantOverrideSpec) DeepCopyInto(out *MimirTenantOverrideSpec) {
	*out = *in
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MimirTenantOverrideSpec.
func (in *MimirTenantOverrideSpec) DeepCopy() *MimirTenantOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(MimirTenantOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MimirTenantOverrideStatus) DeepCopyInto(out *MimirTenantOverrideStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContributingPeers != nil {
		in, out := &in.ContributingPeers, &out.ContributingPeers
		*out = make([]ContributingPeer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MimirTenantOverrideStatus.
func (in *MimirTenantOverrideStatus) DeepCopy() *MimirTenantOverrideStatus {
	if in == nil {
		return nil
	}
	out := new(MimirTenantOverrideStatus)
	in.DeepCopyInto(out)
	return out
}
